import pandas as pd
import numpy as np
from lifelines import AalenAdditiveFitter, KaplanMeierFitter
import pickle
import AalenAdditiveModel as AAM

'''This program imports the nonprofit data set and uses only the uncensored
data to train 100 bootstrap models.  Each model was generated by randomly 
drawing data with replacement from the original uncensored data set.

Note that the results in "Readme.MD" were generated with 10 000 bootstrap models.
However, the resultant pickled file for the list of models would have been too large
to store on github (>8 GB), so only 100 bootstrap models were generated here as
an example.

The data set was loaded from a pickled file called 'cleaned_dataset.p.'

The list of bootstrap models are pickled as 'AAF_100.p'.

'''

#Load the pickled donor dataset
filename = 'cleaned_dataset.p'
fileobject = open(filename, 'rb')
donor_dataset= pickle.load(fileobject)
fileobject.close()

#Call Bootstrap function to perform bootstrap modelling
#Number of bootstrap models = 100
bootstrap_number = 100
AAF_100 = AAM.Bootstrap(donor_dataset, bootstrap_number)

#Pickle the list of bootstrap_number models.
filename = 'AAF_100.p'
fileobject = open(filename, 'wb')
donor_dataset= pickle.dump(AAF_100, fileobject)
fileobject.close()
